url = "https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--glibc--stable-2020.02-2.tar.bz2"
linux_arch = "arm"
uboot_arch = "arm"
cross_compile = "bin/arm-buildroot-linux-gnueabihf-"
